export const games = [
  {
    slug: 'vectoid-td',
    title: 'Vectoid TD 3D',
    iframeSrc: 'https://turbowarp.org/670754400/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'heroic-final',
    title: 'Heroic Final',
    iframeSrc: 'https://turbowarp.org/880482251/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'terminus',
    title: 'Terminus',
    iframeSrc: 'https://turbowarp.org/1106593202/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'elemental',
    title: 'Elemental',
    iframeSrc: 'https://turbowarp.org/844942732/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'evanescent',
    title: 'Evanescent',
    iframeSrc: 'https://turbowarp.org/622009465/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'modern-sonic-engine',
    title: 'Modern Sonic Engine',
    iframeSrc: 'https://turbowarp.org/805845540/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'hyper-flux',
    title: 'Hyper Flux',
    iframeSrc: 'https://turbowarp.org/941979990/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'fortress',
    title: 'Fortress',
    iframeSrc: 'https://turbowarp.org/843560133/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'mysticality',
    title: 'Mysticality',
    iframeSrc: 'https://turbowarp.org/955210840/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'breach',
    title: 'Breach',
    iframeSrc: 'https://turbowarp.org/712527374/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'tadek',
    title: 'Tadek',
    iframeSrc: 'https://turbowarp.org/877636503/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'tadek-jjk',
    title: 'Tadek but JJK'
    iframeSrc: 'https://turbowarp.org//embed'
  }
  {
    slug: 'iframe-copy-2',
    title: '2',
    iframeSrc: 'https://turbowarp.org/121563965/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-copy-3',
    title: '3',
    iframeSrc: 'https://turbowarp.org/1011625528/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-copy-4',
    title: '4',
    iframeSrc: 'https://turbowarp.org/1102118868/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-copy-5',
    title: '5',
    iframeSrc: 'https://turbowarp.org/663115790/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-copy-6',
    title: '6',
    iframeSrc: 'https://turbowarp.org/487580583/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-7',
    title: '7',
    iframeSrc: 'https://turbowarp.org/318927435/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-8',
    title: '8',
    iframeSrc: 'https://turbowarp.org/617067435/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'frontier-2',
    title: 'Frontier 2',
    iframeSrc: 'https://turbowarp.org/58976080/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'zombie-containment',
    title: 'Frontier 3',
    iframeSrc: 'https://turbowarp.org/553882765/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'cast-your-card',
    title: 'Cast Your Card',
    iframeSrc: 'https://turbowarp.org/1203910735/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'super-fighter-re-tournament',
    title: 'Super Fighter Re:Tournament',
    iframeSrc: 'https://turbowarp.org/184411641/embed',
    provider: 'TurboWarp',
  },
  {
    slug: '3-d-tekken-4',
    title: '(3D) Tekken 4 [PS2]',
    iframeSrc: 'https://turbowarp.org/1144143313/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'code-breakers',
    title: 'CodeBreakers',
    iframeSrc: 'https://turbowarp.org/589378166/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'monster-world',
    title: 'Monster World',
    iframeSrc: 'https://turbowarp.org/943379105/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'bleach-orange-shinigami',
    title: 'BLEACH: オレンジ 死神(Orange Shinigami)',
    iframeSrc: 'https://turbowarp.org/1257692578/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'scratch-fighting-jjk',
    title: 'Scratch Fighting Game JJK',
    iframeSrc: 'https://turbowarp.org/1268463919/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'sf-3',
    title: 'Street Fighter III: 3rd Strike',
    iframeSrc: 'https://alexcherry.com/games/sf3rdstrike/',
    provider: 'Alex Cherry',
  },
  {
    slug: 'iframe-11',
    title: 'Iframe 11',
    iframeSrc: 'https://turbowarp.org/536697778/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-12',
    title: 'Iframe 12',
    iframeSrc: 'https://turbowarp.org/873281098/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-13',
    title: 'Iframe 13',
    iframeSrc: 'https://turbowarp.org/121563965/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-14',
    title: 'Iframe 14',
    iframeSrc: 'https://turbowarp.org/139025103/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-2',
    title: 'Iframe 2',
    iframeSrc: 'https://turbowarp.org/189115791/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-3',
    title: 'Iframe 3',
    iframeSrc: 'https://turbowarp.org/171307915/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-4',
    title: 'Iframe 4',
    iframeSrc: 'https://turbowarp.org/315622227/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-5',
    title: 'Iframe 5',
    iframeSrc: 'https://turbowarp.org/277114703/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-6',
    title: 'Iframe 6',
    iframeSrc: 'https://turbowarp.org/174671513/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-copy',
    title: 'Iframe Copy',
    iframeSrc: 'https://turbowarp.org/489159823/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-copy-7',
    title: 'Iframe Copy 7',
    iframeSrc: 'https://turbowarp.org/1268463919/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'deadswitch3',
    title: 'Dead Switch 3',
    iframeSrc: 'https://deadswitch3.com/play/',
    provider: 'Wilken Games',
  },
  {
    slug: 'arsenal-online',
    title: 'Arsenal Online',
    iframeSrc: 'https://arsenalonline.net/play',
    provider: 'Wilken Games',
  },
  {
    slug: 'dinogen-online',
    title: 'Dinogen Online',
    iframeSrc: 'https://dinogenonline.com/play',
    provider: 'Wilken Games',
  },
  {
    slug: 'tactical-weapon-pack-2',
    title: 'Tactical Weapon Pack 2',
    iframeSrc: 'https://html5.gamedistribution.com/b87c4bc6e4604eeeb6fcc3d1b6bf844f/?utm_source=xwilkinx.com&utm_medium=tactical-weapon-pack-2',
    provider: 'Wilken Games',
  }
];