export const games = [
  {
    slug: 'vectoid-td',
    title: 'Vectoid TD 3D',
    iframeSrc: 'https://turbowarp.org/670754400/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'heroic-final',
    title: 'Heroic Final',
    iframeSrc: 'https://turbowarp.org/880482251/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'terminus',
    title: 'Terminus',
    iframeSrc: 'https://turbowarp.org/1106593202/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'elemental',
    title: 'Elemental',
    iframeSrc: 'https://turbowarp.org/844942732/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'evanescent',
    title: 'Evanescent',
    iframeSrc: 'https://turbowarp.org/622009465/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'modern-sonic-engine',
    title: 'Modern Sonic Engine',
    iframeSrc: 'https://turbowarp.org/805845540/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'hyper-flux',
    title: 'Hyper Flux',
    iframeSrc: 'https://turbowarp.org/941979990/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'fortress',
    title: 'Fortress',
    iframeSrc: 'https://turbowarp.org/843560133/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'mysticality',
    title: 'Mysticality',
    iframeSrc: 'https://turbowarp.org/955210840/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'breach',
    title: 'Breach',
    iframeSrc: 'https://turbowarp.org/712527374/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'tadek',
    title: 'Tadek',
    iframeSrc: 'https://turbowarp.org/877636503/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'tadek-jjk',
    title: 'Tadek but JJK',
    iframeSrc: 'https://turbowarp.org/1285719463/embed',
    provider: 'Turbowarp',
  },
  {
    slug: 'iframe-copy-2',
    title: '2',
    iframeSrc: 'https://turbowarp.org/121563965/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-copy-3',
    title: '3',
    iframeSrc: 'https://turbowarp.org/1011625528/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-copy-4',
    title: '4',
    iframeSrc: 'https://turbowarp.org/1102118868/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-copy-5',
    title: '5',
    iframeSrc: 'https://turbowarp.org/663115790/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-copy-6',
    title: '6',
    iframeSrc: 'https://turbowarp.org/487580583/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-7',
    title: '7',
    iframeSrc: 'https://turbowarp.org/318927435/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-8',
    title: '8',
    iframeSrc: 'https://turbowarp.org/617067435/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'frontier-2',
    title: 'Frontier 2',
    iframeSrc: 'https://turbowarp.org/58976080/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'zombie-containment',
    title: 'Frontier 3',
    iframeSrc: 'https://turbowarp.org/553882765/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'cast-your-card',
    title: 'Cast Your Card',
    iframeSrc: 'https://turbowarp.org/1203910735/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'super-fighter-re-tournament',
    title: 'Super Fighter Re:Tournament',
    iframeSrc: 'https://turbowarp.org/184411641/embed',
    provider: 'TurboWarp',
  },
  {
    slug: '3-d-tekken-4',
    title: '(3D) Tekken 4 [PS2]',
    iframeSrc: 'https://turbowarp.org/1144143313/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'code-breakers',
    title: 'CodeBreakers',
    iframeSrc: 'https://turbowarp.org/589378166/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'monster-world',
    title: 'Monster World',
    iframeSrc: 'https://turbowarp.org/943379105/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'bleach-orange-shinigami',
    title: 'BLEACH: オレンジ 死神(Orange Shinigami)',
    iframeSrc: 'https://turbowarp.org/1257692578/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'scratch-fighting-jjk',
    title: 'Scratch Fighting Game JJK',
    iframeSrc: 'https://turbowarp.org/1268463919/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'sf-3',
    title: 'Street Fighter III: 3rd Strike',
    iframeSrc: 'https://alexcherry.com/games/sf3rdstrike/',
    provider: 'Alex Cherry',
  },
  {
    slug: 'iframe-11',
    title: 'Iframe 11',
    iframeSrc: 'https://turbowarp.org/536697778/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-12',
    title: 'Iframe 12',
    iframeSrc: 'https://turbowarp.org/873281098/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-13',
    title: 'Iframe 13',
    iframeSrc: 'https://turbowarp.org/121563965/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-14',
    title: 'Iframe 14',
    iframeSrc: 'https://turbowarp.org/139025103/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-2',
    title: 'Iframe 2',
    iframeSrc: 'https://turbowarp.org/189115791/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-3',
    title: 'Iframe 3',
    iframeSrc: 'https://turbowarp.org/171307915/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-4',
    title: 'Iframe 4',
    iframeSrc: 'https://turbowarp.org/315622227/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-5',
    title: 'Iframe 5',
    iframeSrc: 'https://turbowarp.org/277114703/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-6',
    title: 'Iframe 6',
    iframeSrc: 'https://turbowarp.org/174671513/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-copy',
    title: 'Iframe Copy',
    iframeSrc: 'https://turbowarp.org/489159823/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'jump-showdown-scratch',
    title: 'Jump Showdown Scratch',
    iframeSrc: 'https://turbowarp.org/1291180961/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'iframe-copy-7',
    title: 'Iframe Copy 7',
    iframeSrc: 'https://turbowarp.org/1268463919/embed',
    provider: 'TurboWarp',
  },
  {
    slug: 'deadswitch3',
    title: 'Dead Switch 3',
    iframeSrc: 'https://deadswitch3.com/play/',
    provider: 'Wilken Games',
  },
  {
    slug: 'arsenal-online',
    title: 'Arsenal Online',
    iframeSrc: 'https://arsenalonline.net/play',
    provider: 'Wilken Games',
  },
  {
    slug: 'dinogen-online',
    title: 'Dinogen Online',
    iframeSrc: 'https://dinogenonline.com/play',
    provider: 'Wilken Games',
  },
  {
    slug: 'tactical-weapon-pack-2',
    title: 'Tactical Weapon Pack 2',
    iframeSrc: 'https://html5.gamedistribution.com/b87c4bc6e4604eeeb6fcc3d1b6bf844f/?utm_source=xwilkinx.com&utm_medium=tactical-weapon-pack-2',
    provider: 'Wilken Games',
  },
  {
    slug: 'mk48-io',
    title: 'MK48.io',
    iframeSrc: 'https://mk48.io/',
    provider: 'mk48.io',
  },
  {
    slug: 'antwar-io',
    title: 'AntWar.io',
    iframeSrc: 'https://antwar.io/',
    provider: 'antwar.io',
  },
  {
    slug: 'tyran-io',
    title: 'Tyran.io',
    iframeSrc: 'https://tyran.io',
    provider: 'tyran.io',
  },
  {
    slug: 'stickman-kombat-2d',
    title: 'Stickman Kombat 2D',
    iframeSrc: 'https://games.crazygames.com/en_US/stickman-kombat-2d/index.html?v=1.352',
    provider: 'CrazyGames',
  },
  {
    slug: 'stickman-project-bnw',
    title: 'Stickman Project BnW',
    iframeSrc: 'https://games.crazygames.com/en_US/stickman-project-bnw/index.html?v=1.352',
    provider: 'CrazyGames',
  },
  {
    slug: 'war-the-knights',
    title: 'War the Knights',
    iframeSrc: 'https://games.crazygames.com/en_US/war-the-knights/index.html?v=1.352',
    provider: 'CrazyGames',
  },
  {
    slug: 'yohoho-io',
    title: 'YoHoHo.io',
    iframeSrc: 'https://yohoho.io/',
    provider: 'yohoho.io',
  },
  {
    slug: 'raidfield-2-pjc',
    title: 'Raidfield 2',
    iframeSrc: 'https://games.crazygames.com/en_US/raidfield-2-pjc/index.html?v=1.352',
    provider: 'CrazyGames',
  },
  {
    slug: 'stickman-rebirth',
    title: 'Stickman Rebirth',
    iframeSrc: 'https://games.crazygames.com/en_US/stickman%20Rebirth/index.html?v=1.352',
    provider: 'CrazyGames',
  },
  {
    slug: 'space-wars-battleground',
    title: 'Space Wars Battleground',
    iframeSrc: 'https://games.crazygames.com/en_US/space-wars-battleground/index.html?v=1.352',
    provider: 'CrazyGames',
  },
  {
    slug: 'gravity-arena-shooter',
    title: 'Gravity Arena Shooter',
    iframeSrc: 'https://games.crazygames.com/en_US/gravity-arena-shooter/index.html?v=1.352',
    provider: 'CrazyGames',
  },
  {
    slug: 'funny-blade-magic',
    title: 'Funny Blade & Magic',
    iframeSrc: 'https://games.crazygames.com/en_US/funny-blade-magic/index.html?v=1.352',
    provider: 'CrazyGames',
  },
  {
    slug: 'funny-city-gopniks',
    title: 'Funny City Gopniks',
    iframeSrc: 'https://games.crazygames.com/en_US/funny-city-gopniks/index.html?v=1.352',
    provider: 'CrazyGames',
  },
  {
    slug: 'hero-3-flying-robot',
    title: 'Hero 3: Flying Robot',
    iframeSrc: 'https://games.crazygames.com/en_US/hero-3-flying-robot/index.html?v=1.352',
    provider: 'CrazyGames',
  },
  {
    slug: 'horde-killer-you-vs-100',
    title: 'Horde Killer: You vs 100',
    iframeSrc: 'https://games.crazygames.com/en_US/horde-killer-you-vs-100/index.html?v=1.352',
    provider: 'CrazyGames',
  },
  {
    slug: 'time-shooter-3-swat',
    title: 'Time Shooter 3: SWAT',
    iframeSrc: 'https://games.crazygames.com/en_US/time-shooter-3-swat/index.html?v=1.352',
    provider: 'CrazyGames',
  },
  {
    slug: 'funny-shooter-2',
    title: 'Funny Shooter 2',
    iframeSrc: 'https://games.crazygames.com/en_US/funny-shooter-2/index.html?v=1.352',
    provider: 'CrazyGames',
  },
  {
    slug: 'funny-battle-simulator-2',
    title: 'Funny Battle Simulator 2',
    iframeSrc: 'https://games.crazygames.com/en_US/funny-battle-simulator-2/index.html?v=1.352',
    provider: 'CrazyGames',
  },
  {
    slug: 'bullet-force',
    title: 'Bullet Force',
    iframeSrc: 'https://games.crazygames.com/en_US/bullet-force-multiplayer/index.html?v=1.352',
    provider: 'CrazyGames',
  },
  {
    slug: 'crazygames-unknown-2',
    title: 'Unknown CrazyGames Game 2',
    iframeSrc: 'https://games.crazygames.com/en_US//index.html?v=1.352',
    provider: 'CrazyGames',
  },
  {
    slug: 'monster-battlegrounds',
    title: 'Monster Battlegrounds',
    iframeSrc: 'https://html-classic.itch.zone/html/13241631/Monster_Battlegrounds_(v0_4_1)_html/index.html',
    provider: 'itch.io',
  },
  {
    slug: 'anime-battle',
    title: 'Anime Battle',
    iframeSrc: 'https://www.y8.com/games/anime_battle_4',
    provider: 'GameSlot',
  },
  {
    slug: 'hakai',
    title: 'HAKAI',
    iframeSrc: 'https://html-classic.itch.zone/html/6461953/index.html?v=1732313691',
    provider: 'itch.io',
  },
  {
    slug: 'marvel-vs-capcom',
    title: 'Marvel vs Capcom',
    iframeSrc: 'https://gam.onl/arcade/marvel-vs-capcom-clash-of-super-heroes.html',
    provider: 'emulator.js',
  }
];
